"""renamed tablename from tasks to todo

Revision ID: 35d3dbf5f719
Revises: b354c35db022
Create Date: 2025-12-08 11:59:38.572079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d3dbf5f719'
down_revision: Union[str, Sequence[str], None] = 'b354c35db022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: SQLite does not support ALTER COLUMN. These nullability changes
    # were generated by autogenerate but SQLite will raise a syntax error.
    # Skip altering the columns here; the models already reflect the
    # intended schema. If you need to enforce NOT NULL in SQLite, you must
    # recreate the table (create temp table, copy data, drop old, rename).
    # op.alter_column('otps', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    # op.alter_column('otps', 'otp_code', existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f('ix_todos_owner_id'), 'todos', ['owner_id'], unique=False)
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_todos_owner_id'), table_name='todos')
    # Skipping ALTER COLUMN on SQLite (not supported).
    # op.alter_column('otps', 'otp_code', existing_type=sa.VARCHAR(), nullable=True)
    # op.alter_column('otps', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
