"""upgraded somethings

Revision ID: b354c35db022
Revises: 46b14fd778cd
Create Date: 2025-12-06 12:49:11.766975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b354c35db022'
down_revision: Union[str, Sequence[str], None] = '46b14fd778cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('otps', 'otp_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    op.alter_column('otps', 'otp_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('otps', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
