"""upgraded somethings

Revision ID: b354c35db022
Revises: 46b14fd778cd
Create Date: 2025-12-06 12:49:11.766975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b354c35db022'
down_revision: Union[str, Sequence[str], None] = '46b14fd778cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we skip these operations
    # The schema is already correct in the models
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we skip these operations
    # ### end Alembic commands ###
    pass
